# service definition
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  labels:
    app: chess
spec:
  selector:
      app: chess
  ports:
     - protocol:  
       port: 1883
       targetPort: 1883
  selector:
    app: chess

---
# container definitions
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-w251-final 
spec:
  selector:
    matchLabels:
      app: chess
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: chess
    spec:
      containers:
      - name: chess-live
        image: chess-live
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /dev/video0
          name: webcam
        securityContext:
          privileged: true 
      - name: chess-mosquitto
        image: chess-mosquitto
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1883
      - name: chess-yolo
        image: chess-yolo
        imagePullPolicy: IfNotPresent
        #     - name: logger
        #image: pnarsina1/w251_nx_logger
        #volumeMounts:
        #- mountPath: /logs
        #  name: logs 
        #securityContext:
        #  privileged: true

      volumes:
      - name: webcam
        hostPath:
          path: /dev/video0
      - name: logs
        hostPath:
          path: /home/prabhu/w251/hw3/logs
