#FROM w251/l4t-pytorch:r32.4.4-pth1.7-py3
FROM w251/l4t-pytorch:r32.4.4-pth1.7-py3

# tested on Jetson NX

# Create working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN apt update && apt install -y  libssl-dev
# Copy contents
# COPY . /usr/src/app
RUN git clone https://github.com/ultralytics/yolov5 

WORKDIR /usr/src/app/yolov5

# Install dependencies (pip or conda)
# RUN pip3 install -r requirements.txt


RUN apt update && apt install -y libffi-dev python3-pip curl unzip python3-tk libopencv-dev python3-opencv 
RUN python3 -m pip install -U pip
RUN pip3 install -U gsutil pyyaml tqdm cython torchvision==0.8.2
RUN apt install -y python3-scipy python3-matplotlib python3-numpy
RUN pip3 install git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI
RUN pip3 install jupyter
RUN pip3 install python-chess
RUN pip3 install svglib
RUN pip3 install paho-mqtt

RUN ["apt-get", "install", "-y", "vim"]

# RUN pip3 install requests
# RUN apt install -y python3-pandas
# RUN pip3 install seaborn
RUN pip3 install -U pip
RUN pip list
RUN pip3 install -r requirements.txt
COPY ./ . 
CMD ["python3","detect_chess_mqtt.py"]

